---
# handlers file for mediapeers.zookeeper

- name: restart zookeeper
  service:
    name: zookeeper
    state: restarted

- name: setup systemd
  systemd:
    daemon_reload: yes
    service: zookeeper.service
    enabled: yes
